version: '3.8'

services:
  redis:
    image: redis
    container_name: session-store
    restart: always
    ports:
      - '6379:6379'
    networks:
      - proxy_network

  client:
    image: ghcr.io/hirurg-lybitel/gdmn-crm-client:latest
    container_name: crm_client
    ports:
      - ${NX_APP_PORT}:80
    volumes:
      - type: bind
        source: ssl
        target: /etc/nginx/ssl
        read_only: true
    networks:
      - proxy_network

  server:
    image: ghcr.io/hirurg-lybitel/gdmn-crm-server:latest
    depends_on:
      redis:
        condition: service_started
    container_name: crm_server
    ports:
      - '${NX_SERVER_PORT}:${NX_SERVER_PORT}'
      - '${NX_SOCKET_NOTIFICATIONS_PORT}:${NX_SOCKET_NOTIFICATIONS_PORT}'
      - '${NX_SOCKET_STREAMING_UPDATE_PORT}:${NX_SOCKET_STREAMING_UPDATE_PORT}'
    volumes:
      - type: bind
        source: ssl
        target: /ssl
        read_only: true
    env_file:
      - ./.env
      - ./.env.prod
    environment:
      - TZ=Europe/Minsk
    networks:
      - proxy_network
networks:
  proxy_network:
    external: true
