services:
  client:
    image: ghcr.io/hirurg-lybitel/gdmn-client:latest
    container_name: crm_client
    ports:
      - ${NX_APP_PORT}:80
    networks:
      - proxy_network

  server:
    image: ghcr.io/hirurg-lybitel/gdmn-server:latest
    container_name: crm_server
    ports:
      - "${NX_SERVER_PORT}:${NX_SERVER_PORT}"
      - "${NX_SOCKET_NOTIFICATIONS_PORT}:${NX_SOCKET_NOTIFICATIONS_PORT}"
      - "${NX_SOCKET_STREAMING_UPDATE_PORT}:${NX_SOCKET_STREAMING_UPDATE_PORT}"
    env_file:
      - ./.env
      - ./.env.prod
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
