name: Build Belgiss Dev Client Image
run-name: ${{ github.actor }} triggered Docker client 🖥️ deploying 🐳

on:
  push:
    branches:
      - belgiss-prod
    paths:
      - 'apps/gdmn-nxt-web/**'
      - 'libs/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/belgiss-dev-crm-client
  ENV_SERVER_HOST: ${{ vars.ENV_SERVER_HOST }}
  ENV_SOCKET_NOTIFICATIONS_PORT: ${{ vars.ENV_SOCKET_NOTIFICATIONS_PORT}}
  ENV_SOCKET_STREAMING_UPDATE_PORT: ${{ vars.ENV_SOCKET_STREAMING_UPDATE_PORT }}

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    environment: Belgiss_test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            "NX_SERVER_HOST=${{ env.ENV_SERVER_HOST }}"
            "NX_SOCKET_NOTIFICATIONS_PORT=${{ env.ENV_SOCKET_NOTIFICATIONS_PORT }}"
            "NX_SOCKET_STREAMING_UPDATE_PORT=${{ env.ENV_SOCKET_STREAMING_UPDATE_PORT }}"
          target: client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
