name: Testing variables

on:
  push:
    branches:
      - main

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    name: Test variables
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository secret : $CONTEXT_SECRET"
        echo "overridden variable : $OVERRIDE_VAR"
        echo "variable from shell environment : $env_var"
      env:
        REPOSITORY_VAR: ${{ vars.ENV_CONTEXT_VAR }}
        CONTEXT_SECRET: ${{ vars.ENV_CONTEXT_SECRET }}
        OVERRIDE_VAR: my override variable

    - name: ${{ vars.HELLO_WORLD_STEP }}
      if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ vars.GREET_NAME }}
